### ISSUE TITLE
Panic when required AWS env variables are not defined

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic-provision#5]
`provision` panics when the env vars that the AWS provisioner requires are not defined.
```
./provision aws create -e 1 -m 2 -w 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6382d]

goroutine 1 [running]:
panic(0x52df20, 0xc4200140c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/apprenda/kismatic-provision/provision/aws.prepareToModifyAWS(0x527100, 0xc4200195f0, 0x5d8e04)
	/Users/abrand/Dev/go/src/github.com/apprenda/kismatic-provision/provision/aws/aws.go:201 +0x5d
github.com/apprenda/kismatic-provision/provision/aws.makeInfra(0x200020001, 0x0, 0x0, 0x0, 0x5d8e04, 0x5, 0x0, 0x0)
	/Users/abrand/Dev/go/src/github.com/apprenda/kismatic-provision/provision/aws/aws.go:283 +0xb4
github.com/apprenda/kismatic-provision/provision/aws.AWSCreateCmd.func1(0xc4200db8c0, 0xc42001a600, 0x0, 0x6, 0x0, 0x0)
	/Users/abrand/Dev/go/src/github.com/apprenda/kismatic-provision/provision/aws/aws.go:73 +0x3e
github.com/spf13/cobra.(*Command).execute(0xc4200db8c0, 0xc42001a540, 0x6, 0x6, 0xc4200db8c0, 0xc42001a540)
	/Users/abrand/Dev/go/src/github.com/spf13/cobra/command.go:599 +0x234
github.com/spf13/cobra.(*Command).ExecuteC(0x8e67e0, 0x0, 0x0, 0x0)
	/Users/abrand/Dev/go/src/github.com/spf13/cobra/command.go:689 +0x367
github.com/spf13/cobra.(*Command).Execute(0x8e67e0, 0xc4200db680, 0xc4200001a0)
	/Users/abrand/Dev/go/src/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/Users/abrand/Dev/go/src/github.com/apprenda/kismatic-provision/provision/main.go:24 +0x2d
```

**Comment by dasmb** [comment]
Panic eh? That's no good
